First HW
KittySaur/Card-Game pull request #1
Opened 2022-06-07 03:24 UTC by KittySaur

Сверстана первая страница приложения с выбором сложности игры

2022-06-07 09:01 UTC, mrerberg requested changes

2022-06-07 09:01 UTC, mrerberg commented on css/style.css
> +    background: #C2F5FF;
background-color может?

2022-06-07 21:52 UTC, KittySaur commented on index.html
> +<html lang="en">
Исправила

2022-06-08 08:44 UTC, mrerberg approved these changes

2022-06-09 22:01 UTC, merged